"""Persist and apply MCP configuration generated by the Command Center walkthrough."""

from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path

import config
from backend.schemas.command_center import MCPConfigurationApplyRequest, MCPConfiguredServerRequest


@dataclass(frozen=True, slots=True)
class AppliedMCPConfiguration:
    env_block: str
    env_path: Path
    server_count: int
    format: str


class MCPConfigurationService:
    """Write walkthrough-generated MCP settings into the repo .env and live process."""

    _BLOCK_START = "# Command Center MCP configuration"
    _BLOCK_END = "# End Command Center MCP configuration"
    _MANAGED_EXACT_KEYS = {
        "MCP_ENABLED",
        "EXTERNAL_SUBPROCESS_INTEGRATIONS_ENABLED",
        "MCP_SERVERS_JSON",
        "MCP_TOOL_PREFIX",
    }

    def __init__(self, *, env_path: Path | None = None) -> None:
        self._env_path = env_path or (config.PROJECT_ROOT / ".env")

    def apply(self, payload: MCPConfigurationApplyRequest) -> AppliedMCPConfiguration:
        assignments = self._build_assignments(payload)
        env_block = self._render_env_block(assignments)
        self._write_env_file(assignments)
        self._apply_process_environment(assignments)
        return AppliedMCPConfiguration(
            env_block=env_block,
            env_path=self._env_path,
            server_count=len(payload.servers),
            format=payload.format,
        )

    def _build_assignments(self, payload: MCPConfigurationApplyRequest) -> dict[str, str]:
        if not payload.servers:
            raise ValueError("Provide at least one MCP server configuration.")

        if payload.format == "single" and len(payload.servers) != 1:
            raise ValueError("Single-server format accepts exactly one MCP server.")

        assignments = {
            "MCP_ENABLED": self._bool_value(payload.enable_mcp),
            "EXTERNAL_SUBPROCESS_INTEGRATIONS_ENABLED": self._bool_value(payload.enable_external_integrations),
        }

        normalized_servers = [self._normalize_server(server, index=index) for index, server in enumerate(payload.servers, start=1)]
        if payload.format == "json":
            assignments["MCP_SERVERS_JSON"] = json.dumps(normalized_servers, ensure_ascii=True, separators=(",", ":"))
            return assignments

        if payload.format == "single":
            assignments.update(self._single_server_assignments(normalized_servers[0]))
            return assignments

        for index, server in enumerate(normalized_servers, start=1):
            assignments.update(self._indexed_server_assignments(server, index=index))
        return assignments

    @staticmethod
    def _normalize_server(server: MCPConfiguredServerRequest, *, index: int) -> dict[str, object]:
        command = server.command.strip()
        if not command:
            raise ValueError(f"Server {index} is missing a command.")

        args = [arg.strip() for arg in server.args if arg.strip()]
        env = {key.strip(): str(value).strip() for key, value in server.env.items() if key.strip()}
        normalized: dict[str, object] = {
            "name": server.name.strip() or f"server-{index}",
            "command": command,
            "args": args,
            "tool_prefix": server.tool_prefix.strip() or "mcp",
        }
        cwd = (server.cwd or "").strip()
        if cwd:
            normalized["cwd"] = cwd
        if env:
            normalized["env"] = env
        return normalized

    @staticmethod
    def _single_server_assignments(server: dict[str, object]) -> dict[str, str]:
        assignments = {
            "MCP_SERVER_NAME": str(server["name"]),
            "MCP_SERVER_COMMAND": str(server["command"]),
            "MCP_SERVER_ARGS": json.dumps(server.get("args", []), ensure_ascii=True, separators=(",", ":")),
            "MCP_TOOL_PREFIX": str(server["tool_prefix"]),
        }
        if "cwd" in server:
            assignments["MCP_SERVER_CWD"] = str(server["cwd"])
        env = server.get("env")
        if isinstance(env, dict) and env:
            assignments["MCP_SERVER_ENV_JSON"] = json.dumps(env, ensure_ascii=True, separators=(",", ":"))
        return assignments

    @staticmethod
    def _indexed_server_assignments(server: dict[str, object], *, index: int) -> dict[str, str]:
        prefix = f"MCP_SERVER_{index}_"
        assignments = {
            f"{prefix}NAME": str(server["name"]),
            f"{prefix}COMMAND": str(server["command"]),
            f"{prefix}ARGS": json.dumps(server.get("args", []), ensure_ascii=True, separators=(",", ":")),
            f"{prefix}TOOL_PREFIX": str(server["tool_prefix"]),
        }
        if "cwd" in server:
            assignments[f"{prefix}CWD"] = str(server["cwd"])
        env = server.get("env")
        if isinstance(env, dict) and env:
            assignments[f"{prefix}ENV_JSON"] = json.dumps(env, ensure_ascii=True, separators=(",", ":"))
        return assignments

    def _write_env_file(self, assignments: dict[str, str]) -> None:
        existing_lines = self._env_path.read_text(encoding="utf-8").splitlines() if self._env_path.exists() else []
        preserved_lines: list[str] = []
        for line in existing_lines:
            stripped = line.strip()
            if stripped in {self._BLOCK_START, self._BLOCK_END}:
                continue
            key = self._extract_key(stripped)
            if key is not None and self._is_managed_key(key):
                continue
            preserved_lines.append(line)

        while preserved_lines and not preserved_lines[-1].strip():
            preserved_lines.pop()

        output_lines = list(preserved_lines)
        if output_lines:
            output_lines.append("")
        output_lines.append(self._BLOCK_START)
        output_lines.extend(self._render_env_block(assignments).splitlines())
        output_lines.append(self._BLOCK_END)
        self._env_path.write_text("\n".join(output_lines) + "\n", encoding="utf-8")

    def _apply_process_environment(self, assignments: dict[str, str]) -> None:
        for key in list(os.environ):
            if self._is_managed_key(key):
                os.environ.pop(key, None)

        for key, value in assignments.items():
            os.environ[key] = value

        config.MCP_ENABLED = assignments["MCP_ENABLED"].lower() == "true"
        config.EXTERNAL_SUBPROCESS_INTEGRATIONS_ENABLED = (
            assignments["EXTERNAL_SUBPROCESS_INTEGRATIONS_ENABLED"].lower() == "true"
        )

    def _render_env_block(self, assignments: dict[str, str]) -> str:
        return "\n".join(f"{key}={self._quote_value(value)}" for key, value in assignments.items())

    @classmethod
    def _is_managed_key(cls, key: str) -> bool:
        return key in cls._MANAGED_EXACT_KEYS or key.startswith("MCP_SERVER_")

    @staticmethod
    def _extract_key(stripped_line: str) -> str | None:
        if not stripped_line or stripped_line.startswith("#") or "=" not in stripped_line:
            return None
        return stripped_line.split("=", 1)[0].strip()

    @staticmethod
    def _quote_value(value: str) -> str:
        if not value:
            return '""'

        if "#" not in value and "'" not in value and not any(character.isspace() for character in value):
            return value

        if "'" not in value:
            return f"'{value}'"

        escaped = value.replace('"', '\\"')
        return f'"{escaped}"'

    @staticmethod
    def _bool_value(enabled: bool) -> str:
        return "true" if enabled else "false"